---

- name: Ensure required variables are set.
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:
    - create_vm_template__proxmox_node_name
    - create_vm_template__proxmox_node_bridge_name
    - create_vm_template__proxmox_api_ip
    - create_vm_template__proxmox_api_token_secret
    - create_vm_template__template_name
    - create_vm_template__template_image_url
    - create_vm_template__template_vmid
    - create_vm_template__template_root_password

- name: Create template, refreshed if needed.
  block:
    - name: Stop and/or remove existing VM.
      community.general.proxmox_kvm:
        api_host: "{{ create_vm_template__proxmox_api_ip }}"
        api_user: "{{ create_vm_template__proxmox_api_user }}"
        api_token_id: "{{ create_vm_template__proxmox_api_token_id }}"
        api_token_secret: "{{ create_vm_template__proxmox_api_token_secret }}"
        node: "{{ create_vm_template__proxmox_node_name }}"
        vmid: "{{ create_vm_template__template_vmid }}"
        state: "{{ item }}"
        timeout: 300
      loop:
        - stopped
        - absent
      ignore_errors: true

    - name: Download image.
      become: true
      ansible.builtin.get_url:
        url: "{{ create_vm_template__template_image_url }}"
        dest: "{{ create_vm_template__temporary_image_path }}"
        mode: "0644"
        force: false

    - name: Bake image with virt-customize.
      become: true
      shell: |
        set -e
        virt-customize -a "{{ create_vm_template__temporary_image_path }}" \
          --install qemu-guest-agent,cloud-init,openssh-server \
          --update \
          --run-command 'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && apt-get clean' \
          --run-command 'rm -rf /var/lib/apt/lists/*' \
          --run-command 'cloud-init clean' \
          --truncate /etc/machine-id \
          --run-command 'rm -f /etc/netplan/*.yaml /etc/network/interfaces /etc/systemd/network/*.network' || true

    - name: Compress image.
      become: true
      shell: |
        set -e
        qemu-img convert -O qcow2 -c -o preallocation=off \
          "{{ create_vm_template__temporary_image_path }}" \
          "{{ create_vm_template__temporary_compressed_image_path }}"

    - name: Create empty VM.
      community.general.proxmox_kvm:
        api_host: "{{ create_vm_template__proxmox_api_ip }}"
        api_user: "{{ create_vm_template__proxmox_api_user }}"
        api_token_id: "{{ create_vm_template__proxmox_api_token_id }}"
        api_token_secret: "{{ create_vm_template__proxmox_api_token_secret }}"
        node: "{{ create_vm_template__proxmox_node_name }}"
        vmid: "{{ create_vm_template__template_vmid }}"
        name: "{{ create_vm_template__template_name }}"
        cores: "{{ create_vm_template__vm_cores }}"
        memory: "{{ create_vm_template__vm_memory }}"
        net:
          net0: "virtio,bridge={{ create_vm_template__proxmox_node_bridge_name }}"
        ostype: l26
        scsihw: virtio-scsi-pci
        bios: seabios
        machine: q35
        agent: enabled=1
        onboot: false
        tags: [ "building-template" ]
        state: present

    - name: Import disk.
      become: true
      shell: |
        set -e
        qm importdisk "{{ create_vm_template__template_vmid }}" \
          "{{ create_vm_template__temporary_compressed_image_path }}" \
          "{{ create_vm_template__vm_storage }}" \
          --format qcow2

    - name: Set & resize disk.
      become: true
      shell: |
        set -e
        qm set {{ create_vm_template__template_vmid }} --scsi0 {{ create_vm_template__vm_storage }}:0
        qm set {{ create_vm_template__template_vmid }} --boot order=scsi0
        qm resize {{ create_vm_template__template_vmid }} scsi0 {{ create_vm_template__vm_disk }}

    - name: Configure VM.
      community.general.proxmox_kvm:
        api_host: "{{ create_vm_template__proxmox_api_ip }}"
        api_user: "{{ create_vm_template__proxmox_api_user }}"
        api_token_id: "{{ create_vm_template__proxmox_api_token_id }}"
        api_token_secret: "{{ create_vm_template__proxmox_api_token_secret }}"
        node: "{{ create_vm_template__proxmox_node_name }}"
        vmid: "{{ create_vm_template__template_vmid }}"
        name: "{{ create_vm_template__template_name }}"
        serial:
          serial0: socket
        vga: serial0
        ciuser: debian
        cipassword: "{{ create_vm_template__template_root_password }}"
        nameservers: [ "1.1.1.1" ]
        sshkeys: "{{ create_vm_template__ssh_public_key }}"
        update: true
        state: present
        timeout: 600

    - name: Remove existing cloud-init disk (if any)
      become: true
      shell: |
        set -e
        if qm config {{ create_vm_template__template_vmid }} | grep -q '^scsi2:'; then
          qm set {{ create_vm_template__template_vmid }} --delete scsi2
        fi
        find /var/lib/vz/images/{{ create_vm_template__template_vmid }}/ -name "vm-{{ create_vm_template__template_vmid }}-cloudinit.qcow2" -delete || true
      args:
        warn: false

    - name: Regenerate cloud-init config.
      become: true
      shell: |
        set -e
        qm set {{ create_vm_template__template_vmid }} --scsi2 {{ create_vm_template__vm_storage }}:cloudinit
        qm cloudinit update {{ create_vm_template__template_vmid }}
    #
    # - name: Convert VM to template.
    #   community.general.proxmox_kvm:
    #     api_host: "{{ create_vm_template__proxmox_api_ip }}"
    #     api_user: "{{ create_vm_template__proxmox_api_user }}"
    #     api_token_id: "{{ create_vm_template__proxmox_api_token_id }}"
    #     api_token_secret: "{{ create_vm_template__proxmox_api_token_secret }}"
    #     node: "{{ create_vm_template__proxmox_node_name }}"
    #     vmid: "{{ create_vm_template__template_vmid }}"
    #     name: "{{ create_vm_template__template_name }}"
    #     state: template
    #     timeout: 120

