---

- name: Setup 'auto-update apt packages' cronjob.
  become: true
  ansible.builtin.cron:
    name: auto-update apt packages
    hour: 3
    minute: 0
    job: apt-get update -y && apt-get full-upgrade -y
    user: root
    state: present

- name: Setup 'auto-clean apt packages' cronjob.
  become: true
  ansible.builtin.cron:
    name: auto-clean apt packages.
    hour: 3
    minute: 15
    weekday: 6
    job: apt-get autoclean -y && apt-get autoremove -y
    user: root
    state: present

