---
- name: Setup k3s.
  hosts: all[1]
  become: true
  vars:
    proxmox_node_name: "{{ host.name }}"
    proxmox_node_id: "{{ inventory_hostname.split('_')[-1] | int }}"
    proxmox_node_ip: "{{ host.ipv4 }}"
    proxmox_node_bridge_ip: "{{ host.bridge.ipv4 }}"
    proxmox_node_bridge_name: "{{ host.bridge.name }}"
    # ---
    proxmox_api_ip: "{{ proxmox_node_ip }}"
    proxmox_api_token_secret: "{{ proxmox.api_token }}"
    # ---
    vm_root_password: "{{ ansible_become_pass }}"
    vm_common_tags: [ k3s ]

  tasks:
    - name: Create K3s master(s).
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/create-vm"
      loop: "{{ k3s.masters }}"
      loop_control:
        index_var: i
        loop_var: master_ipv4
      vars:
        create_vm_node_name: "{{ proxmox_node_name }}"
        create_vm_node_bridge_name: "{{ proxmox_node_bridge_name }}"
        create_vm_proxmox_api_ip: "{{ proxmox_api_ip }}"
        create_vm_proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"
        # ---
        create_vm_vmid: "{{ proxmox_node_id }}{{ common.k3s.masters_ips_start_range + i }}"
        create_vm_hostname: "k3s-master-{{ proxmox_node_id }}-{{ i + 1 }}"
        create_vm_user_password: "{{ vm_root_password }}"
        create_vm_gateway: "{{ proxmox_node_bridge_ip }}"
        create_vm_ip_with_cidr: "{{ master_ipv4 }}"
        create_vm_tags: "{{ vm_common_tags + ['master'] }}"


    # - name: Create K3s node(s).
