---
- name: Setup k3s.
  hosts: all[1]
  become: true
  vars:
    proxmox_node_name: "{{ host.name }}"
    proxmox_node_id: "{{ inventory_hostname.split('_')[-1] | int }}"
    proxmox_node_ip: "{{ host.ipv4 }}"
    proxmox_node_bridge_ip: "{{ host.bridge.ipv4 }}"
    proxmox_node_bridge_name: "{{ host.bridge.name }}"
    # ---
    proxmox_api_ip: "{{ proxmox_node_ip }}"
    proxmox_api_token_secret: "{{ proxmox.api_token }}"
    # ---
    vm_id: 60
    vm_vmid: "{{ proxmox_node_id }}{{ '%02d' | format(vm_id) }}"
    vm_hostname: "k3s-master-{{ proxmox_node_id }}-1"
    vm_root_password: "{{ ansible_become_pass }}"
    vm_ip_with_cidr: "10.0.1.60"
    vm_tags: [ k3s, master ]

  tasks:
    - name: Create k3s masters.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/create-vm"
      vars:
        create_vm_node_name: "{{ proxmox_node_name }}"
        create_vm_proxmox_api_ip: "{{ proxmox_api_ip }}"
        create_vm_proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"
        create_vm_vmid: "{{ vm_vmid }}"
        create_vm_hostname: "{{ vm_hostname }}"
        create_vm_user_password: "{{ vm_root_password }}"
        create_vm_gateway: "{{ proxmox_node_bridge_ip }}"
        create_vm_ip_with_cidr: "{{ vm_ip_with_cidr }}"
        create_vm_tags: "{{ vm_tags }}"

