---

- name: Configure apt sources
  become: true
  ansible.builtin.template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install required apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  when: packages is defined and packages | length > 0

