---

- name: configure apt sources
  become: true
  ansible.builtin.template:
    src: templates/etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: update & upgrade apt packages
  become: true
  ansible.builtin.apt:
    # update_cache: yes
    upgrade: dist # Ensures a fill system upgrade.

- name: install required apt packages, if missing
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  when: packages is defined

- name: setup 'auto-update apt packages' cronjob
  become: true
  ansible.builtin.cron:
    name: auto-update apt packages
    hour:   "3"
    minute: "0"
    job: apt-get update -y && apt-get upgrade -y
    state: present
    user: root

- name: setup 'auto-clean apt packages' cronjob
  become: true
  ansible.builtin.cron:
    name: auto-clean apt packages
    hour:    "3"
    minute:  "15"
    weekday: "6"
    job: apt-get autoclean -y && apt-get autoremove -y
    state: present
    user: root

