---

# ▖ ▖▄▖▄▖
# ▛▖▌▌▌▚
# ▌▝▌▛▌▄▌
#

# - name: Setup NAS.
#   hosts: nas
#   roles:
#
#     # packages.
#     - instances/nas/base
#
#     # nfs server.
#     - instances/nas/nfs-server
#
# ▖▖    ▗
# ▙▌▛▌▛▘▜▘▛▘
# ▌▌▙▌▄▌▐▖▄▌
#
#

# - name: Setup proxmox-hosts.
#   hosts: proxmox_hosts
#   roles:
#
#     # packages.
#     - instances/proxmox-hosts/base
#
#     # networking & dns.
#     - instances/proxmox-hosts/networking-and-dns
#
#     # tailscale.
#     - instances/proxmox-hosts/tailscale
#
#     # systemd.
#     - instances/proxmox-hosts/systemd
#
#     # nfs client.
#     - instances/proxmox-hosts/nfs-client
#
#     # observability.
#     - instances/proxmox-hosts/opentelemetry-collector
#
# ▄▖       ▜   ▗
# ▐ █▌▛▛▌▛▌▐ ▀▌▜▘█▌▛▘
# ▐ ▙▖▌▌▌▙▌▐▖█▌▐▖▙▖▄▌
#        ▌

# - import_playbook: playbooks/proxmox-templates/debian-12-nocloud-amd64/main.yml

# ▖ ▖▖▄▖ ▄▖    ▗   ▘
# ▌ ▚▘▌  ▌ ▛▌▛▌▜▘▀▌▌▛▌█▌▛▘▛▘
# ▙▖▌▌▙▖ ▙▖▙▌▌▌▐▖█▌▌▌▌▙▖▌ ▄▌
#

# # PLEASE NOTE: order matters here.
# - import_playbook: services/lxc/nginx-reverse-proxy/main.yml
# - import_playbook: services/lxc/prometheus/main.yml
# - import_playbook: services/lxc/grafana/main.yml

# ▖▖▄▖
# ▙▘▙▌▛▘
# ▌▌▙▌▄▌
#

- import_playbook: services/vms/k3s/main.yml

# ▄     ▌
# ▌▌▛▌▛▘▙▘█▌▛▘
# ▙▘▙▌▙▖▛▖▙▖▌

# TODO:

# ▖▖▄▖
# ▙▘▙▌▛▘
# ▌▌▙▌▄▌
#

