---

- name: Setup DNS.
  hosts: dns
  roles:

    # Raspbian optimization (remove GUI, minimize disk usage).
    - instances/dns/raspbian-optimization

    # Packages.
    - instances/dns/base

    # Tailscale.
    - instances/dns/tailscale

    # Pi-hole (installation + configuration).
    - instances/dns/pihole

    # Observability.
    - instances/dns/opentelemetry-collector

# ▖ ▖▄▖▄▖
# ▛▖▌▌▌▚
# ▌▝▌▛▌▄▌
#

# - name: Setup NAS.
#  hosts: nas
#  roles:

    # Packages.
#    - instances/nas/base

    # Tailscale.
#    - instances/nas/tailscale

# ▖▖    ▗
# ▙▌▛▌▛▘▜▘▛▘
# ▌▌▙▌▄▌▐▖▄▌
#

- name: Setup proxmox-hosts.
  hosts: proxmox_hosts
  roles:

    # packages.
    - instances/proxmox-hosts/base

    # networking & dns.
    - instances/proxmox-hosts/networking-and-dns

    # tailscale.
    - instances/proxmox-hosts/tailscale

    # systemd.
    - instances/proxmox-hosts/systemd

    # nfs client.
    - instances/proxmox-hosts/nfs-client

    # observability.
    #- instances/proxmox-hosts/opentelemetry-collector

# ▄▖       ▜   ▗
# ▐ █▌▛▛▌▛▌▐ ▀▌▜▘█▌▛▘
# ▐ ▙▖▌▌▌▙▌▐▖█▌▐▖▙▖▄▌
#        ▌

# - import_playbook: playbooks/proxmox-templates/debian-12-nocloud-amd64/main.yml

# ▖ ▖▖▄▖ ▄▖    ▗   ▘
# ▌ ▚▘▌  ▌ ▛▌▛▌▜▘▀▌▌▛▌█▌▛▘▛▘
# ▙▖▌▌▙▖ ▙▖▙▌▌▌▐▖█▌▌▌▌▙▖▌ ▄▌
#

# # PLEASE NOTE: order matters here.
# - import_playbook: services/lxc/nginx-reverse-proxy/main.yml
# - import_playbook: services/lxc/prometheus/main.yml
# - import_playbook: services/lxc/grafana/main.yml

# ▖▖▄▖
# ▙▘▙▌▛▘
# ▌▌▙▌▄▌
#

# - import_playbook: services/vms/k3s/main.yml

# ▄     ▌
# ▌▌▛▌▛▘▙▘█▌▛▘
# ▙▘▙▌▙▖▛▖▙▖▌

# TODO:

# ▖▖▄▖ ▄▖
# ▙▘▌▌▛▘
# ▌▌▙▌▄▌
#
