---

# ▖▖    ▗
# ▙▌▛▌▛▘▜▘▛▘
# ▌▌▙▌▄▌▐▖▄▌
#

# - name: Setup hosts.
#   hosts: all
#   roles:
#
#     # packages.
#     - hosts/apt
#
#     # networking & dns.
#     - hosts/networking-and-dns
#
#     # cronjobs.
#     - hosts/crons

# ▖ ▖▄▖▄▖
# ▛▖▌▙▖▚
# ▌▝▌▌ ▄▌
#

# - name: Setup NFS (servers).
#   hosts: jmpa_server_1
#   roles: [hosts/nfs-server]

# - name: Setup NFS (client).
#   hosts: jmpa_server_2, jmpa_server_3
#   roles: [hosts/nfs-client]

# ▖ ▖▖▄▖ ▄▖    ▗   ▘
# ▌ ▚▘▌  ▌ ▛▌▛▌▜▘▀▌▌▛▌█▌▛▘▛▘
# ▙▖▌▌▙▖ ▙▖▙▌▌▌▐▖█▌▌▌▌▙▖▌ ▄▌
#

# - import_playbook: proxmox/lxc/tailscale/main.yml
- import_playbook: proxmox/lxc/nginx-reverse-proxy/main.yml
# - import_playbook: proxmox/lxc/buildkite-runner/main.yml

# ▖▖▄▖
# ▙▘▙▌▛▘
# ▌▌▙▌▄▌

# TODO:

# ▄     ▌
# ▌▌▛▌▛▘▙▘█▌▛▘
# ▙▘▙▌▙▖▛▖▙▖▌

# TODO:

# --- --- ---
# ▖ ▖  ▗
# ▛▖▌▛▌▜▘█▌▛▘
# ▌▝▌▙▌▐▖▙▖▄▌
#
#
# https://patorjk.com/software/taag/#p=display&h=1&v=1&f=miniwi&t=LOGO
#
