---

# ▖▖    ▗
# ▙▌▛▌▛▘▜▘▛▘
# ▌▌▙▌▄▌▐▖▄▌
#

# - name: Setup proxmox-hosts.
#   hosts: all
#   roles:
#
#     # packages.
#     - instances/proxmox-hosts/apt
#
#     # networking & dns.
#     - instances/proxmox-hosts/networking-and-dns
#
#     # cronjobs.
#     - instances/proxmox-hosts/crons
#
#     # systemd.
#     - instances/proxmox-hosts/systemd
#
#     # observability.
#     - instances/proxmox-hosts/opentelemetry-collector

# ▄▖       ▜   ▗
# ▐ █▌▛▛▌▛▌▐ ▀▌▜▘█▌▛▘
# ▐ ▙▖▌▌▌▙▌▐▖█▌▐▖▙▖▄▌
#        ▌

# - import_playbook: playbooks/proxmox-templates/debian-12-nocloud-amd64/main.yml

# ▖ ▖▄▖▄▖
# ▛▖▌▙▖▚
# ▌▝▌▌ ▄▌
#

# - name: Setup NFS (servers).
#   hosts: all[0]
#   roles: [instances/proxmox-hosts/nfs-server]
#
# - name: Setup NFS (clients).
#   hosts: all[1:]
#   roles: [instances/proxmox-hosts/nfs-client]

# ▖ ▖▖▄▖ ▄▖    ▗   ▘
# ▌ ▚▘▌  ▌ ▛▌▛▌▜▘▀▌▌▛▌█▌▛▘▛▘
# ▙▖▌▌▙▖ ▙▖▙▌▌▌▐▖█▌▌▌▌▙▖▌ ▄▌
#

# # PLEASE NOTE: order matters here.
- import_playbook: services/lxc/tailscale/main.yml
# - import_playbook: services/lxc/nginx-reverse-proxy/main.yml
# - import_playbook: services/lxc/prometheus/main.yml
# - import_playbook: services/lxc/grafana/main.yml

# ▖▖▄▖
# ▙▘▙▌▛▘
# ▌▌▙▌▄▌
#

# - import_playbook: services/vms/k3s/main.yml

# ▄     ▌
# ▌▌▛▌▛▘▙▘█▌▛▘
# ▙▘▙▌▙▖▛▖▙▖▌

# TODO:

# --- --- ---
# ▖ ▖  ▗
# ▛▖▌▛▌▜▘█▌▛▘
# ▌▝▌▙▌▐▖▙▖▄▌
#
#
#
#

