---
# Setup Tailscale on DNS instance.

- name: Include shared Tailscale setup tasks
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/tailscale/setup.yml"
  vars:
    tailscale_advertise_routes: "{{ ansible_host }}/32"
    tailscale_accept_dns: false
