---

- name: Install required apt packages.
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  when: packages is defined and packages | length > 0

- name: Mount network directory.
  become: true
  ansible.posix.mount:
    name: "{{ nfs.dest }}"
    src: "{{ nfs.src }}:{{ nfs.dest }}"
    fstype: nfs
    state: mounted
    opts: defaults
    dump: 0
    passno: 0

