---

- name: Download otelcol
  ansible.builtin.get_url:
    url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otel_version }}/{{ otel_deb_file }}"
    dest: "/tmp/{{ otel_deb_file }}"

- name: Install OpenTelemetry Collector
  become: true
  ansible.builtin.apt:
    deb: "/tmp/{{ otel_deb_file }}"

- name: Update /etc/otelcol/config.yaml
  become: true
  ansible.builtin.template:
    src: etc/otelcol/config.yaml.j2
    dest: /etc/otelcol/config.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart otelcol

- name: Ensure OpenTelemetry Collector is enabled and started
  become: true
  ansible.builtin.systemd:
    name: otelcol
    enabled: yes
    state: started

- name: Cleanup .deb file
  ansible.builtin.file:
    path: "/tmp/{{ otel_deb_file }}"
    state: absent

