---

- name: Setup Prometheus.
  hosts: all
  become: true
  vars:
    proxmox_node_name: "{{ host.name }}"
    proxmox_node_id: "{{ inventory_hostname.split('_')[-1] | int }}"
    proxmox_node_ip: "{{ host.ipv4 }}"
    proxmox_node_bridge_ip: "{{ host.bridge.ipv4 }}"
    proxmox_node_bridge_name: "{{ host.bridge.name }}"
    # ---
    proxmox_api_ip: "{{ proxmox_node_ip }}"
    proxmox_api_token_secret: "{{ proxmox.api_token }}"
    # ---
    lxc_id: "{{ services.prometheus.container_id }}"
    lxc_vmid: "{{ proxmox_node_id }}{{ '%02d' | format(lxc_id) }}"
    lxc_hostname: prometheus
    lxc_root_password: "{{ ansible_become_pass }}"
    lxc_ip_with_cidr: "{{ services.prometheus.ipv4_with_cidr }}"
    lxc_tags: [ prometheus, monitoring ]

  tasks:
    - name: Create LXC container.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/create-lxc"
      vars:
        create_lxc__proxmox_node_ip: "{{ proxmox_node_ip }}"
        create_lxc__proxmox_node_name: "{{ proxmox_node_name }}"
        create_lxc__proxmox_node_bridge_ip: "{{ proxmox_node_bridge_ip }}"
        create_lxc__proxmox_node_bridge_name: "{{ proxmox_node_bridge_name }}"
        create_lxc__proxmox_api_ip: "{{ proxmox_api_ip }}"
        create_lxc__proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"
        create_lxc__lxc_vmid: "{{ lxc_vmid }}"
        create_lxc__lxc_hostname: "{{ lxc_hostname }}"
        create_lxc__lxc_root_password: "{{ lxc_root_password }}"
        create_lxc__lxc_subnet: "{{ lxc_ip_with_cidr }}"
        create_lxc__lxc_tags: "{{ lxc_tags }}"
      register: create_container

    - name: Copy /etc/prometheus/prometheus.yml
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/copy-file-to-lxc"
      vars:
        copy_file_to_lxc__proxmox_node_ip: "{{ proxmox_node_ip }}"
        copy_file_to_lxc__lxc_vmid: "{{ lxc_vmid }}"
        copy_file_to_lxc__file_source: etc/prometheus/prometheus.yml.j2
        copy_file_to_lxc__file_destination: /etc/prometheus/prometheus.yml
        copy_file_to_lxc__show_difference: true
        copy_file_to_lxc__copy_to_node_no_log: false
        copy_file_to_lxc__copy_to_lxc_no_log: false

    - name: Install Prometheus.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/execute-script-in-lxc"
      vars:
        execute_script_in_lxc___proxmox_node_ip: "{{ proxmox_node_ip }}"
        execute_script_in_lxc___lxc_vmid: "{{ lxc_vmid }}"
        execute_script_in_lxc___script_source: tmp/install-prometheus.sh.j2
        execute_script_in_lxc___script_destination: /tmp/install_prometheus.sh
        execute_script_in_lxc___copy_to_node_show_difference: false

    - name: Check Prometheus is running.
      ansible.builtin.command: pct exec {{ lxc_vmid }} -- systemctl is-active --quiet prometheus.service
      register: service_check
      failed_when: service_check.rc != 0
