---
- name: "Ensure required variables are set"
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:
    - id
    - container_id
    - hostname
    - node
    - api_host
    - api_token_secret
    - password

- name: "Stop LXC container {{ hostname }} if it exists"
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ node }}"
    vmid: "{{ vmid }}"
    state: stopped
  ignore_errors: true

- name: "Remove LXC container {{ hostname }} if it exists"
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ node }}"
    vmid: "{{ vmid }}"
    state: absent
  ignore_errors: true

- name: "Create and start LXC container {{ hostname }}"
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ node }}"
    vmid: "{{ vmid }}"
    hostname: "{{ hostname }}"
    ostemplate: "{{ ostemplate }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    # disk: "{{ disk }}"
    password: "{{ password }}"
    netif:
      net0: "name=eth0,gw={{ ipv4_gateway }},ip={{ ipv4_address }}/{{ ipv4_address_cidr }},bridge={{ bridge }}"
    unprivileged: true
    features:
      - nesting=1
    pubkey: "{{ lookup('file', ssh_key) }}"
    onboot: 1
    state: present

- name: "Start LXC Container: {{ hostname }}"
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ node }}"
    vmid: "{{ vmid }}"
    state: started

- name: "Wait for SSH to become available on LXC Container: {{ hostname }}"
  wait_for:
    host: "{{ ipv4_address }}"
    port: 22
    delay: 10
    timeout: 30

