---

- name: "Ensure required variables are set"
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:
    - id
    - container_id
    - hostname
    - node
    - api_host
    - api_token_secret
    - password

- name: "Check if LXC container {{ hostname }} exists"
  shell: "pct list | awk '{print $1}' | grep -w {{ vmid }}"
  register: container_check
  ignore_errors: true
  changed_when: false

- name: "Stop LXC container {{ hostname }} if it exists"
  command: "pct stop {{ vmid }}"
  when: container_check.rc == 0
  ignore_errors: true
  register: stop_result
  changed_when: stop_result.rc == 0

- name: "Destroy LXC container {{ hostname }} if it exists"
  command: "pct destroy {{ vmid }}"
  when: container_check.rc == 0
  register: destroy_result
  changed_when: destroy_result.rc == 0

- name: "Create LXC Container: {{ hostname }}"
  become: true
  community.general.proxmox:
    vmid: "{{ vmid }}"
    hostname: "{{ hostname }}"
    node: "{{ node }}"

    # auth.
    api_host: "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user: "{{ api_user }}"
    password: "{{ password }}"

    # container resources.
    ostemplate: "{{ ostemplate }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    disk: "{{ disk }}"

    # networking.
    netif: "{{ netif }}"

    # ssh.
    pubkey: "{{ lookup('file', ssh_key) }}"

    # extras.
    state: "{{ state }}"
    timeout: "{{ timeout }}"
    unprivileged: true
    features:
      - nesting=1
      - keyctl=1

- name: "Check if LXC container {{ hostname }} is running"
  shell: "pct status {{ vmid }} 2>/dev/null | grep -q 'status: running' || true"
  register: container_status
  ignore_errors: true
  changed_when: false

- name: "Start LXC Container: {{ hostname }}"
  command: "pct start {{ vmid }}"
  when: container_status.rc != 0

- name: "Wait for SSH to become available on LXC Container: {{ hostname }}"
  wait_for:
    host: "{{ ipv4_address }}"
    port: 22
    delay: 10
    timeout: 60
