---
# Setup Tailscale on Proxmox host with additional host-specific services.

- name: Include shared Tailscale setup tasks
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/tailscale/setup.yml"
  vars:
    tailscale_advertise_routes: "{{ ansible_host }}/32,{{ host.bridge.subnet }}/{{ host.bridge.ipv4_cidr }}"
    tailscale_tags: ["{{ instance_name | regex_replace('-[0-9]+$', '') }}"]

- name: Add Tailscale nginx reverse proxy routing service.
  become: true
  ansible.builtin.template:
    src: etc/systemd/system/tailscale-nginx-reverse-proxy-routing.service
    dest: /etc/systemd/system/tailscale-nginx-reverse-proxy-routing.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon.
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Tailscale nginx reverse proxy routing service.
  become: true
  ansible.builtin.systemd:
    name: tailscale-nginx-reverse-proxy-routing
    enabled: true
    state: started
