---

- name: Setup buildkite-runner
  hosts: jmpa_server_3
  become: true
  vars:
    domain: "{{ hostvars[inventory_hostname].domain }}"

    # proxmox - node.
    proxmox_node_name: "{{ inventory_hostname | replace('_', '-') }}"
    proxmox_node_id: "{{ inventory_hostname.split('_')[-1] | int }}"
    proxmox_node_ip: "{{ hostvars[inventory_hostname].host_ipv4 }}"
    proxmox_node_bridge_ip: "{{ hostvars[inventory_hostname].host_bridge_ipv4 }}"
    proxmox_node_bridge_name: "{{ hostvars[inventory_hostname].host_bridge_name }}"

    # proxmox - api.
    proxmox_api_ip: "{{ proxmox_node_ip }}"
    proxmox_api_token_secret: "{{ hostvars[inventory_hostname].proxmox_api_token }}"

    # lxc - container.
    lxc_container_id: 70
    lxc_container_vmid: "{{ proxmox_node_id }}{{ '%02d' | format(lxc_container_id) }}"
    lxc_container_hostname: buildkite-runner
    lxc_container_root_password: "{{ hostvars[inventory_hostname].ansible_become_pass }}"
    lxc_container_ip: "{{ hostvars[inventory_hostname].host_bridge_default_ipv4_prefix }}.{{ proxmox_node_id }}.{{ lxc_container_id }}"
    lxc_container_ip_cidr: "{{ hostvars[inventory_hostname].host_bridge_default_ipv4_cidr }}"
    lxc_container_tags: [ buildkite, runner ]

  tasks:

    - name: Create LXC Container.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/create-lxc"
      vars:
        # proxmox - node.
        create_lxc_node_ip: "{{ proxmox_node_ip }}"
        create_lxc_node_name: "{{ proxmox_node_name }}"
        create_lxc_node_bridge_ip: "{{ proxmox_node_bridge_ip }}"
        create_lxc_node_bridge_name: "{{ proxmox_node_bridge_name }}"

        # proxmox - api.
        create_lxc_proxmox_api_ip: "{{ proxmox_api_ip }}"
        create_lxc_proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"

        # lxc - container.
        create_lxc_container_id: "{{ lxc_container_vmid }}"
        create_lxc_container_hostname: "{{ lxc_container_hostname }}"
        create_lxc_container_root_password: "{{ lxc_container_root_password }}"
        create_lxc_container_subnet: "{{ lxc_container_ip }}/{{ lxc_container_ip_cidr }}"
        create_lxc_container_tags: "{{ lxc_container_tags }}"
      register: create_container



