---

- name: Setup Prometheus.
  hosts: jmpa_server_3
  become: true
  vars:
    proxmox_node_name: "{{ host.name }}"
    proxmox_node_id: "{{ inventory_hostname.split('_')[-1] | int }}"
    proxmox_node_ip: "{{ host.ipv4 }}"
    proxmox_node_bridge_ip: "{{ host.bridge.ipv4 }}"
    proxmox_node_bridge_name: "{{ host.bridge.name }}"
    # ---
    proxmox_api_ip: "{{ proxmox_node_ip }}"
    proxmox_api_token_secret: "{{ proxmox.api_token }}"
    # ---
    lxc_container_id: "{{ services.prometheus.container_id }}"
    lxc_container_vmid: "{{ proxmox_node_id }}{{ '%02d' | format(lxc_container_id) }}"
    lxc_container_hostname: prometheus
    lxc_container_root_password: "{{ ansible_become_pass }}"
    lxc_container_subnet: "{{ services.prometheus.ipv4_with_cidr }}"
    lxc_container_tags: [ prometheus, monitoring ]

  tasks:
    - name: Create LXC Container.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/create-lxc"
      vars:
        create_lxc:
          node_ip: "{{ proxmox_node_ip }}"
          node_name: "{{ proxmox_node_name }}"
          node_bridge_ip: "{{ proxmox_node_bridge_ip }}"
          node_bridge_name: "{{ proxmox_node_bridge_name }}"
          proxmox_api_ip: "{{ proxmox_api_ip }}"
          proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"
          container_id: "{{ lxc_container_vmid }}"
          container_hostname: "{{ lxc_container_hostname }}"
          container_root_password: "{{ lxc_container_root_password }}"
          container_subnet: "{{ lxc_container_subnet }}"
          container_tags: "{{ lxc_container_tags }}"
      register: create_container

    - name: Copy /etc/prometheus/prometheus.yml
      when: create_container is success
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/copy-file-to-lxc"
      vars:
        copy_file_to_lxc:
          node_ip: "{{ proxmox_node_ip }}"
          container_id: "{{ lxc_container_vmid }}"
          file_source: etc/prometheus/prometheus.yml.j2
          file_destination: /etc/prometheus/prometheus.yml
          show_difference: true
          copy_to_node_no_log: false
          copy_to_lxc_no_log: false

    - name: Install Prometheus.
      when: create_container is success
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/execute-script-in-lxc"
      vars:
        execute_script_in_lxc:
          node_ip: "{{ proxmox_node_ip }}"
          container_id: "{{ lxc_container_vmid }}"
          script_source: tmp/install-prometheus.sh.j2
          script_destination: /tmp/install_prometheus.sh
          copy_to_node_show_difference: false

