---

- name: Ensure required variables are set.
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:

    # proxmox - node.
    - create_lxc_node_ip
    - create_lxc_node_name
    - create_lxc_node_bridge_ip
    - create_lxc_node_bridge_name

    # proxmox - api.
    - create_lxc_proxmox_api_ip
    - create_lxc_proxmox_api_token_secret

    # lxc - container.
    - create_lxc_container_id
    - create_lxc_container_hostname
    - create_lxc_container_root_password
    - create_lxc_container_subnet
    - create_lxc_container_tags

- name: Create LXC Container, refreshed if needed.
  block:
    - name: Stop and / or remove existing LXC container.
      community.general.proxmox:
        api_host: "{{ create_lxc_proxmox_api_ip }}"
        api_user: "{{ create_lxc_proxmox_api_user }}"
        api_token_id: "{{ create_lxc_proxmox_api_token_id }}"
        api_token_secret: "{{ create_lxc_proxmox_api_token_secret }}"
        node: "{{ create_lxc_node_name }}"
        vmid: "{{ create_lxc_container_id }}"
        state: "{{ item }}"
        unprivileged: true
      loop:
        - stopped
        - absent
      ignore_errors: true

    - name: Create LXC container.
      community.general.proxmox:
        api_host: "{{ create_lxc_proxmox_api_ip }}"
        api_user: "{{ create_lxc_proxmox_api_user }}"
        api_token_id: "{{ create_lxc_proxmox_api_token_id }}"
        api_token_secret: "{{ create_lxc_proxmox_api_token_secret }}"
        node: "{{ create_lxc_node_name }}"
        vmid: "{{ create_lxc_container_id }}"
        hostname: "{{ create_lxc_container_hostname }}"
        ostemplate: "{{ create_lxc_container_ostemplate }}"
        cores: "{{ create_lxc_container_cores }}"
        memory: "{{ create_lxc_container_memory }}"
        # disk: "{{ create_lxc_container_disk }}"
        tags: "{{ create_lxc_container_tags }}"
        password: "{{ create_lxc_container_root_password }}"
        netif:
          net0: "name=eth0,gw={{ create_lxc_node_bridge_ip }},ip={{ create_lxc_container_subnet }},bridge={{ create_lxc_node_bridge_name }}"
        nameserver: "{{ create_lxc_node_ip }}"
        unprivileged: true
        features:
          - nesting=1
        pubkey: "{{ lookup('file', create_lxc_container_ssh_pubkey) }}"
        onboot: 1
        state: present

    - name: Start LXC container.
      community.general.proxmox:
        api_host: "{{ create_lxc_proxmox_api_ip }}"
        api_user: "{{ create_lxc_proxmox_api_user }}"
        api_token_id: "{{ create_lxc_proxmox_api_token_id }}"
        api_token_secret: "{{ create_lxc_proxmox_api_token_secret }}"
        node: "{{ create_lxc_node_name }}"
        vmid: "{{ create_lxc_container_id }}"
        hostname: "{{ create_lxc_container_hostname }}"
        state: started

    - name: Wait for SSH to become available.
      wait_for:
        host: "{{ create_lxc_container_subnet | split('/') | first }}"
        port: 22
        delay: 10
        timeout: 30

    - name: Install dependencies inside LXC container.
      ansible.builtin.include_role:
        name: "{{ root_playbook_directory }}/roles/execute-script-in-lxc"
      vars:
        execute_script_in_lxc_node_ip: "{{ create_lxc_node_ip }}"
        execute_script_in_lxc_container_id: "{{ create_lxc_container_id }}"
        execute_script_in_lxc_script_source: "{{ root_playbook_directory }}/roles/create-lxc/templates/install-deps.sh.j2"
        execute_script_in_lxc_script_destination: /tmp/install_deps.sh

  rescue:
    - name: Error encountered, clean up LXC container if able.
      community.general.proxmox:
        api_host: "{{ create_lxc_proxmox_api_ip }}"
        api_user: "{{ create_lxc_proxmox_api_user }}"
        api_token_id: "{{ create_lxc_proxmox_api_token_id }}"
        api_token_secret: "{{ create_lxc_proxmox_api_token_secret }}"
        node: "{{ create_lxc_node_name }}"
        vmid: "{{ create_lxc_container_id }}"
        state: "{{ item }}"
        unprivileged: true
      loop:
        - stopped
        - absent
      ignore_errors: true

