---

- name: Install required apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  when: packages is defined and packages | length > 0

- name: Create network directory
  become: true
  file:
    path: /mnt/share
    state: directory
    mode: '0777'

- name: Update /etc/exports
  become: true
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Refresh exportfs
  become: true
  command: exportfs -a

- name: Restart nfs-kernel-service
  become: true
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted

