---

- name: Ensure required variables are set.
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:

    # proxmox - node.
    - node_ip

    # lxc - container.
    - container_id

    # script.
    - script_source
    - script_destination

- name: Setup temporary directory.
  ansible.builtin.set_fact:
    temporary_directory: "/tmp/ansible/{{ node_ip }}/{{ container_id }}/{{ role_path | basename }}_{{ ansible_date_time.epoch }}"

- name: Setup temporary directory filepath.
  ansible.builtin.set_fact:
    temporary_directory_filepath: "{{ temporary_directory }}/{{ script_destination | basename }}"

- name: Ensure temporary directory exists on Proxmox node.
  ansible.builtin.file:
    path: "{{ temporary_directory }}"
    state: directory
    mode: "0755"
  delegate_to: "{{ node_ip }}"

- name: Copy file to Proxmox node.
  ansible.builtin.template:
    src:  "{{ script_source }}"
    dest: "{{ temporary_directory_filepath }}"
    mode: "{{ script_mode }}"
  delegate_to: "{{ node_ip }}"
  diff: "{{ copy_to_node_show_difference }}"
  no_log: "{{ copy_to_node_show_logs }}"

- name: Copy file into LXC container via pct.
  ansible.builtin.shell: |
    pct push "{{ container_id }}" "{{ temporary_directory_filepath }}" "{{ script_destination }}"
  delegate_to: "{{ node_ip }}"
  no_log: "{{ copy_to_lxc_show_logs }}"

- name: Execute script inside LXC Container.
  ansible.builtin.shell: |
    lxc-attach -n "{{ container_id }}" -- chmod +x "{{ script_destination }}"
    lxc-attach -n "{{ container_id }}" -- "{{ script_destination }}"
  delegate_to: "{{ node_ip }}"
  no_log: "{{ execute_script_show_logs }}"

- name: Clean up file from Proxmox node.
  ansible.builtin.file:
    path: "{{ temporary_directory }}"
    state: absent
  delegate_to: "{{ node_ip }}"

- name: Clean up script inside LXC container.
  ansible.builtin.shell: |
    lxc-attach -n "{{ container_id }}" -- rm -f "{{ script_destination }}"
  delegate_to: "{{ node_ip }}"

