---

- name: Ensure required variables are set.
  fail:
    msg: "Required variable {{ item }} is missing!"
  when: vars[item] is not defined
  loop:

    # node.
    - node_ip

    # container.
    - container_vmid

    # script.
    - script_source
    - script_destination

- name: Copy script into LXC Container.
  ansible.builtin.include_role:
    name: "{{ root_playbook_directory }}/roles/copy-file-to-lxc"
  vars:
    node_ip: "{{ node_ip }}"
    container_vmid: "{{ container_vmid }}"
    file_source: "{{ script_source }}"
    file_destination: "{{ script_destination }}"
    file_show_difference: "{{ copy_show_difference }}"

- name: Execute script inside LXC Container.
  ansible.builtin.shell: |
    lxc-attach -n "{{ container_vmid }}" -- chmod +x "{{ script_destination }}"
    lxc-attach -n "{{ container_vmid }}" -- "{{ script_destination }}"
  delegate_to: "{{ node_ip }}"
  no_log: "{{ execute_no_log }}"

- name: Clean up script inside LXC container.
  ansible.builtin.shell: |
    lxc-attach -n "{{ container_vmid }}" -- rm -f "{{ script_destination }}"
  delegate_to: "{{ node_ip }}"

