---

- name: Restart 'networking' service.
  become: true
  ansible.builtin.systemd:
    name: networking
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart 'dnsmasq' service.
  become: true
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true
    daemon_reload: true

