---

# proxmox.
proxmox_api_user: root@pam
proxmox_api_token_id: proxmox-api-token

# container.
container_vmid: "{{ node_id }}{{ container_id }}"
container_ostemplate: lxc:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
container_cores: 4
container_memory: 2048
# container_disk: 2G
container_ssh_pubkey: "{{ lookup('env', 'HOME') + '/.ssh/id_ed25519.pub' }}"

