---

- name: Update /etc/network/interfaces
  become: true
  ansible.builtin.template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: true

# - name: Update /etc/hosts
#   become: true
#   ansible.builtin.template:
#     src: templates/etc/hosts
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: '0644'
#     backup: true


