apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-suite
  namespace: argocd
  labels:
    app.kubernetes.io/name: arr-suite
    app.kubernetes.io/part-of: media-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jmpa-io/homelab.git
    targetRevision: HEAD
    path: services/k8s/arr-suite

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: monitoring-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jmpa-io/homelab.git
    targetRevision: HEAD
    path: services/k8s/observability

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
