---

- name: Install required apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  when: packages is defined and packages | length > 0

- name: Ensure networking.service.d directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/networking.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add auto-restart service for networking.service.d
  become: true
  ansible.builtin.template:
    src: etc/systemd/system/networking.service.d/auto-restart.conf
    dest: /etc/systemd/system/networking.service.d/auto-restart.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    # NOTE: no notify here as networking is restarted & systemd is reloaded below.

- name: Update /etc/network/interfaces
  become: true
  ansible.builtin.template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart networking

- name: Update /etc/hosts
  become: true
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Update /etc/resolv.conf
  become: true
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Update /etc/dnsmasq.conf
  become: true
  ansible.builtin.template:
    src: etc/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart dnsmasq
