---

- name: Restart 'networking' service.
  become: true
  ansible.builtin.systemd:
    name: networking
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart 'dnsmasq' service.
  become: true
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
    daemon_reload: yes

